# Project information
site_name: Cloaks | Return
site_url: https://www.cloaks.cn
site_author: Cloaks
site_description: >-
  欢迎来到我的博客！这里是我分享个人见解、技术文章、生活点滴和创意的地方。在这里，你将看到关于编程、技术创新、前沿趋势、以及我对生活和工作的思考与感悟。我希望我的文章能够启发你，让你收获新的知识和灵感。如果你对某些话题感兴趣，欢迎留下评论与我讨论，也可以订阅我的博客，第一时间获取最新更新。
  
  感谢你的访问，希望你在这里找到你感兴趣的内容！

# Repository
repo_name: cloakscn/cloakscn.github.io
repo_url: https://github.com/cloakscn/cloakscn.github.io

# Copyright
copyright: |
  Copyright &copy; 2018 - 2024 Cloaks <a href="https://beian.miit.gov.cn/" target="_blank">晋ICP备19014927号-3</a><br/>
  <span id="busuanzi_container_site_pv">
    本站总访问量<span id="busuanzi_value_site_pv"></span>次
  </span> |
  <span id="busuanzi_container_site_uv">
    本站访客数<span id="busuanzi_value_site_uv"></span>人次
  </span> 

# Configuration
theme:
  icon:
    annotation: material/plus-circle
  name: material
  language: zh
  custom_dir: overrides
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.ico
  logo: assets/favicon.ico
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.footnote.tooltips
    - content.tabs.link
    - content.tooltips
    - header.autohide
    - navigation.path
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    # navigation.prune is not compatible with navigation.expand,
    # as navigation expansion requires the complete navigation structure.
    # - navigation.expand
    # - navigation.sections
    # - navigation.prune
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference


# Plugins
plugins:
  - glightbox
  - tags
  - blog:
      blog_toc: true
      post_slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
      post_slugify_separator: _
      post_url_date_format: yyyy/MM
      post_url_format: "posts/{date}/{file}"
  - rss:
      match_path: blog/posts/.* 
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags
      comments_path: "#__comments"
  - social:
      cards_layout_options:
        font_family: Noto Sans SC
        logo: assets/favicon.ico
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true

# Additional configuration
extra:
  # music: 8074820398 # 侧耳倾听
  consent:
    title: Cookie consent | Cookie 同意
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
      <br/>
      我们使用 cookie 来识别您的重复访问和偏好，并衡量我们文档的有效性以及用户是否找到了他们正在搜索的内容。经您同意，您正在帮助我们改进我们的文档。

  status:
    new: Recently added
    deprecated: Deprecated
  analytics:
    provider: google
    property: G-45SCRDG8S7
    feedback:
      title: 此页面有帮助吗？
      ratings:
        - icon: material/emoticon-happy-outline
          name: 此页面很有帮助。
          data: 1
          note: >-
            感谢您的反馈!
        - icon: material/emoticon-sad-outline
          name: 此页面可以改进。
          data: 0
          note: >-
            感谢您的反馈！使用我们的<a href="..." target="_blank" rel="noopener">反馈表</a>帮助我们改进此页面。
  social:
    - icon: simple/rss
      link: https://cloaks.cn/feed_rss_created.xml
    - icon: fontawesome/brands/github
      link: https://github.com/cloakscn
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/u/cloaks
    - icon: material/email
      link: mailto:cloaks@qq.com
    - icon: material/google-analytics
      link: https://analytics.google.com/analytics/web/#/p299634585/reports/intelligenthome?params=_u..nav%3Dmaui
    - icon: simple/googleadsense
      link: https://www.google.com/adsense/new/u/0/pub-3907145727941275/onboarding
# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      # permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  # math support
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - assets/javascripts/katex.js
  - assets/javascripts/mermaid.js
  - https://cdn.jsdelivr.net/npm/mermaid@11.3.0/dist/mermaid.min.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

extra_css:
  - https://unpkg.com/katex@0/dist/katex.min.css

not_in_nav: |
  /tutorials/**/*.md

# Page tree
nav:
  - 首页:
      - index.md
      # - about.md
      # - 共享文本: https://privatebin.icloudnative.io/
  - 往期精粹:
      - 高级架构师:
          - ruankao/index.md
          - 基础知识:
              - ruankao/basics computer.md
              - ruankao/basics embedded.md
              - ruankao/basics network.md
              - ruankao/basics enterprise-informatization.md
              - ruankao/basics information security.md
              - ruankao/basics system engineering.md
              - ruankao/basics software engineering.md
              - ruankao/basics database-design.md
              - ruankao/basics intellectual property rights.md
          - 中级知识:
              - ruankao/medium software architecture.md
              - ruankao/medium system-quality-attributes-and-architecture-assessment.md
              - ruankao/medium reliability.md
              - ruankao/medium software architecture evolution.md
              - ruankao/medium future.md
          - 高级知识:
              - ruankao/advanced information-system-architecture.md
              - ruankao/advanced hierarchical.md
              - ruankao/advanced cloud-native.md
              - ruankao/advanced service-oriented.md
              - ruankao/advanced embedded.md
              - ruankao/advanced communication system.md
              - ruankao/advanced security architecture.md
              - ruankao/advanced web.md
          - 论文写作:
              - ruankao/paper.md
      - 设计模式: 
          - design-patterns/index.md
          - 创建型模式:
              - design-patterns/creational-patterns/singleton.md
              - design-patterns/creational-patterns/prototype.md
              - design-patterns/creational-patterns/factory.md
              - design-patterns/creational-patterns/abstract-factory.md
          - 建造者模式:
              - design-patterns/structural-patterns/adapter.md
              - design-patterns/structural-patterns/facade.md
              - design-patterns/structural-patterns/composite.md
              - design-patterns/structural-patterns/proxy.md
              - design-patterns/structural-patterns/decorator.md
              - design-patterns/structural-patterns/bridge.md
          - 行为模式:
              - design-patterns/behavioral-patterns/template-method.md
              - design-patterns/behavioral-patterns/state.md
              - design-patterns/behavioral-patterns/strategy.md
              - design-patterns/behavioral-patterns/chain-of-responsibility.md
              - design-patterns/behavioral-patterns/command.md
              - design-patterns/behavioral-patterns/observer.md
              - design-patterns/behavioral-patterns/mediator.md
              - design-patterns/behavioral-patterns/visitor.md
              - design-patterns/behavioral-patterns/iterator.md
      - 重构: 
          - refactoring/index.md
          - 什么是重构:
              - refactoring/what-is-refactoring/technical-debt.md
              - refactoring/what-is-refactoring/clean-code.md
              - refactoring/what-is-refactoring/when.md
              - refactoring/what-is-refactoring/how-to.md
          - 什么代码需要重构？:
              - refactoring/code-smells/index.md
              - 臃肿的代码:
                  # - refactoring/code-smells/bloaters/long-method.md
                  # - refactoring/code-smells/bloaters/large-class.md
                  # - refactoring/code-smells/bloaters/primitive-obsession.md
                  - refactoring/code-smells/bloaters/long-parameter-list.md
                  # - refactoring/code-smells/bloaters/data-clumps.md
              - Dispensables:
                  - refactoring/code-smells/dispensables/data-class.md
          - 解决方案:
              - refactoring/techniques/index.md
              - Composing Methods:
                  - refactoring/techniques/composing-methods/extract-method.md
                  - refactoring/techniques/composing-methods/replace-temp-with-query.md
                  - refactoring/techniques/composing-methods/split-temporary-variable.md
              - Moving Features between Objects:
                  - refactoring/techniques/moving-features-between-objects/move-method.md
              - Organizing Data:
                  - refactoring/techniques/organizing-data/encapsulate-field.md
                  - refactoring/techniques/organizing-data/encapsulate-collection.md
                  # - refactoring/techniques/organizing-data/self-encapsulate-field.md
                  # - refactoring/techniques/organizing-data/replace-type-code-with-subclass.md
              - 简化方法调用:
                  - refactoring/techniques/simplifying-method-calls/replace-parameter-with-method-call.md
                  - refactoring/techniques/simplifying-method-calls/preserve-whole-object.md
                  - refactoring/techniques/simplifying-method-calls/remove-parameter.md
                  - refactoring/techniques/simplifying-method-calls/introduce-parameter-object.md
                  - refactoring/techniques/simplifying-method-calls/add-parameter.md
                  - refactoring/techniques/simplifying-method-calls/remove-setting-method.md
                  - refactoring/techniques/simplifying-method-calls/hide-method.md
                  - refactoring/techniques/simplifying-method-calls/separate-query-from-modifier.md
                  - refactoring/techniques/simplifying-method-calls/rename-method.md
  - 博客:
      - blog/index.md
  # - 社区: https://phpbb.itycu.cn